### ISSUE TITLE
Couldn't load Flash plug-in.

### ISSUE THREAD

**Issue by xwal** [joinAero/qtcefclient#1]
Hello,when I run this compile and run the app,it doesn't work for flash.

**Comment by joinAero** [comment]
我默认阻止了插件的加载。所以需要先将`cefclient\client_handler.h`192行`OnBeforePluginLoad()`改为`return false`。

参见`include\cef_request_handler.h`内`OnBeforePluginLoad()`函数的注释：Return true to block loading of the plugin.

然后得自己加载flash插件。参见`include\cef_web_plugin.h`内`CefAddWebPluginPath()`与`CefAddWebPluginDirectory()`这两个函数。

你可以在`cefclient\qcefwebview.cpp`内213行`CefBrowserHost::CreateBrowser()`后添加如下代码：

```
CefAddWebPluginPath(/* flash plugin path here*/);
CefRefreshWebPlugins();
```

另外，我只试了chrome的flash plugin, 但运行crash。在chrome地址栏输入`chrome://plugins/`可以查看其插件位置信息。

其官方issues里有解决此问题的方法：[Issue 130: Enhancement: Load chrome flash plugin](https://code.google.com/p/chromiumembedded/issues/detail?id=130)。

希望有所帮助^^。

**Comment by joinAero** [comment]
又试了下，flash系统插件，你也可以这样：

关于 [Adobe Flash Player 插件](https://support.google.com/chrome/answer/108086?hl=zh-Hans)

安装完后，在以下目录，可以看到`NPSWFxxx.dll`。

32位: `C:\Windows\System32\Macromed\Flash`
64位: `C:\Windows\SysWOW64\Macromed\Flash`

我这win7 32位，如下加了插件路径，测试flash小游戏可以玩儿了。

```
CefAddWebPluginDirectory(CefString("C:\\Windows\\System32\\Macromed\\Flash"));
CefRefreshWebPlugins();
```

**Comment by xwal** [comment]
非常感谢，帮了大忙了~.~。最近在弄这个CEF要移植到Qt下，就卡在了Flash这个地方。

**Comment by cosmos180** [comment]
hi 咨询一个问题 设置成settings.single_process = true 退出的时候 崩溃 不知道怎么办了
