### ISSUE TITLE
生成第二个QCefWebView对象无法填充整个Widget

### ISSUE THREAD

**Issue by xwal** [joinAero/qtcefclient#2]
你好，我连续生成两个QCefWebView对象，第二个对象无法填充整个Widget，只在左上角区域内，resize也无法随窗口变化。

**Comment by joinAero** [comment]
Resizes `QCefWebView`，走的是`ResizeBrowser()`，其中：

```
CefWindowHandle hwnd =
        g_handler->GetBrowser()->GetHost()->GetWindowHandle();
```

它获得记录的Browser窗口句柄，然后通过`DeferWindowPos()`来调节的窗口大小的。

但需要注意的是，这里`g_handler`是全局对象，当你`GetBrowser()`时，只能获得最后创建的Browser。

在`client_handler.cpp`179行`OnAfterCreated()`内，`m_Browser = browser;`赋的值。

所以说，目前QCefWebView只能是一个主窗口。如果确实需要同时有两个的话，可以：
1. 把`g_handler`改为QCefWebView的成员属性。
2. `m_Browser`类似`m_PopupBrowsers`管理起来，`GetBrowser()`时能获得正确的Browser。

以上。

**Comment by xwal** [comment]
谢谢！通过‘把g_handler改为QCefWebView的成员属性’确实可以实现，有个问题是现在的浏览器可以在一个Client中以New Tab的形式打开一个网页，在CEF中如果显示地打开一个新网页是以New一个QCefWebView的方式，还是以其他的什么方式呢

**Comment by joinAero** [comment]
New Tab 应该是以 New QCefWebView 来实现。
1. New QCefWebView 所做的是通过`CefBrowserHost::CreateBrowser()`来创建 CefBrowser 。
2. CefBrowser 注释说明是： Class used to represent a browser window 。其只表示一个浏览器窗口。

多 Tabs 的话，应该是需要创建多个浏览器窗口的。这可以从 ，Chrome 浏览器 New Tab 时与`CefBrowserHost::CreateBrowser()`时，两者都会新开渲染进程的行为上的相似性看出来。

另外，浏览器引擎的初始化应该是在CEF初始化进行的，`CreateBrowser()`则只是开个窗口进行渲染而已。
